name: Integration Tests (charm-ci)

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or ref to test'
        required: false
        default: 'main'

permissions:
  actions: read
  contents: read
  packages: write

jobs:
  integration-test:
    uses: javierdelapuente/charm-ci/.github/workflows/integration-test.yml@main
    secrets: inherit
    with:
      working-directory: .
