name: Publish (charm-ci)

on:
  push:
    branches:
      - main

permissions:
  actions: read
  contents: read

jobs:
  publish:
    uses: canonical/charm-ci/.github/workflows/publish-artifacts.yml@main
    with:
      channel: latest/edge
      integration-workflow-name: integration-test-charm-ci.yaml
    secrets:
      CHARMHUB_TOKEN: ${{ secrets.CHARMHUB_TOKEN }}
