name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    uses: canonical/charm-ci/.github/workflows/publish-artifacts.yml@main
    permissions:
      actions: read
      contents: write
    with:
      channel: latest/edge
      integration-workflow-name: integration-test.yaml
    secrets:
      CHARMHUB_TOKEN: ${{ secrets.CHARMHUB_TOKEN }}
